spring.application.name=escuelasMadrid

# 1. Configuración del puerto para Railway
# Railway asigna un puerto dinámico; si no existe, usa el 8080 por defecto
server.port=${PORT:8080}

# 2. Configuración de MongoDB
# Usamos una variable de entorno para la URI. 
# En local usará tu base de datos y en Railway la que configures en el panel.
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/AyuntamientoMadrid}

# 3. Configuración de errores (para que tu página de error muestre mensajes)
spring.web.error.include-message=always