spring.application.name=escuelasMadrid

# 1. puerto para Railway
# Railway asigna un puerto ; si no existe, usa el 8080 por defecto
server.port=${PORT:8080}

# 2. Config de MongoDB
# Usamos una variable de entorno para la URI. 
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/AyuntamientoMadrid}

# 3. errores (para la pag de error muestre mensajes)
spring.web.error.include-message=always